### ISSUE TITLE
Twitter link not working

### ISSUE THREAD

**Issue by mritzmann** [claudiosmweb/author-bio-box#7]
One my Website, the Twitter Link will not display correct.

Twitter Username in the Wordpress Profile settings:
![twitter1](https://cloud.githubusercontent.com/assets/4533780/11917639/12dd05b2-a710-11e5-83f9-79043a663572.png)

Output on the page:
`<a target="_blank" href="http://RitzmannMarkus" class="bio-icon bio-icon-twitter"></a>`

Is there a known bug?

**Comment by claudiosmweb** [comment]
Maybe wrong description, put your twitter link then,

**Comment by mritzmann** [comment]
@claudiosmweb Yes, but:

![wp_twitter_user](https://cloud.githubusercontent.com/assets/4533780/11918981/e2e39bf2-a744-11e5-80c6-b631ca2ff299.gif)

It won't work.

**Comment by claudiosmweb** [comment]
Ohh, we don't ask for `Twitter @username`, see: https://github.com/claudiosmweb/author-bio-box/blob/master/includes/admin/class-author-bio-box-admin.php#L139

Seems like have another plugin overriding it.
Not an issue with this plugin, just two plugins using the same ID for `twitter`.

**Comment by mritzmann** [comment]
Oh. You are right! https://wordpress.org/plugins/twitter/ was the problem.
